name: "Scan for vulnerabilities"
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  vulnerability:
    name: Nightly Vulnerability Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - master
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache dependencies
        uses: actions/cache@v2.1.3
        continue-on-error: true
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Check
        id: check
        run: mvn -B -U -DskipTests package dependency-check:check
