name: Release
on:
  release:
    types: [ published ]
  workflow_dispatch: { }
jobs:
  test:
    name: Test release
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  deploy:
    name: Deploy artifacts
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
  release:
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - name: Attach artifacts to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ needs.deploy.outputs.artifacts_archive_path }}
          asset_name: ${{ needs.deploy.outputs.artifacts_archive_path }}
          asset_content_type: application/zip
