name: Test
on:
  workflow_dispatch: { }
  workflow_call:
    secrets:
      TC_CLOUD_TOKEN:
        required: true
jobs:
  core-cloud:
    env:
      TC_CLOUD_CONCURRENCY: 4
    name: Test (Cloud) - core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build & Copy exporter
        run: >
          ./mvnw -B -T1C -DskipTests -DskipChecks install
      - name: Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}
      - name: Test
        timeout-minutes: 20
        env:
          TCC_ENABLED: true
        run: >
          ./mvnw -B -Pparallel-tests -DforkCount=1C -DskipChecks -pl core verify
      - name: Terminate Testcontainers Cloud Client active sessions
        if: always()
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          action: terminate
      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cloud-core-test-results
          path: "**/target/surefire-reports/**"
          retention-days: 3
  core-local:
    name: Test (Local) - core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build & Copy exporter
        run: >
          ./mvnw -B -T1C -DskipTests -DskipChecks install
      - name: Test
        timeout-minutes: 20
        # cannot run tests in parallel when using the local daemon
        run: >
          ./mvnw -B -DskipChecks -Plocal-test -pl core verify
      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: local-core-test-results
          path: "**/target/surefire-reports/**"
          retention-days: 3
  engine:
    env:
      TC_CLOUD_CONCURRENCY: 4
    name: Test (Cloud) - engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build & Copy exporter
        run: >
          ./mvnw -B -T1C -DskipTests -DskipChecks install
      - name: Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}
      - name: Test
        timeout-minutes: 20
        env:
          TCC_ENABLED: true
        run: >
          ./mvnw -B -Pparallel-tests -DforkCount=1C -DskipChecks -pl engine verify
      - name: Terminate Testcontainers Cloud Client active sessions
        if: always()
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          action: terminate
      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cloud-engine-test-results
          path: "**/target/surefire-reports/**"
          retention-days: 3
  exporter:
    name: Test (Local) - exporter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build
        run: ./mvnw -B -DskipTests -DskipChecks install
      - name: Test
        timeout-minutes: 20
        run: >
          ./mvnw -B -DskipChecks -pl exporter-test verify
      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: local-exporter-test-results
          path: "**/target/surefire-reports/**"
          retention-days: 3
